version: '3.8'
services:
  db:
    image: mysql:8.0
    cap_add:
      - SYS_NICE
    restart: always
    environment:
      - MYSQL_DATABASE=highload_social_network
      - MYSQL_ROOT_PASSWORD=root
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
      timeout: 10s
      retries: 5
    ports:
      - '127.0.0.1:33066:3306'
      - '3306:3306'
    volumes:
      - db:/var/lib/mysql
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
  hsn:
    container_name: hsn
    build:
      context: ./
    image: hsn-api
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8090:8090"
    environment:
      NODE_ENV: production
      DB_HOST: db:3306
      DB_USER: root
      DB_PASSWORD: root
      DB_NAME: highload_social_network
    links:
      - db
    volumes:
      - ./:/src
volumes:
  db:
    driver: local